version: '3'
services:

  mysql:
    image: mysql:8.0.15
    container_name: mysql
    environment:
      - MYSQL_DATABASE=qualidade-ar
      - MYSQL_ROOT_PASSWORD=s3cr3t
      - MYSQL_USER=qauser
      - MYSQL_PASSWORD=qapass
    volumes:
      - ./qualidade-ar.sql:/docker-entrypoint-initdb.d/qualidade-ar.sql
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password

  mysql_admin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_admin
    environment:
      - PMA_HOST=mysql
    volumes:
      - mysql_admin_data:/sessions
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  mysql_data:
  mysql_admin_data:
